id: P650A46AC
initial_creation_type: input
source_metadata:
  title: Calling the Guru from Afar
  language: en
  description: 'Devotional texts belonging to the genre of Calling the Guru from Afar
    (bla ma rgyang ''bod):'
  volume:
    0e1898e06f884735887328611b604969:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    737cc5399375434b97f3a7cf4f3e3f93:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Prayers
    2d2e070b4ac54f8dbe21245893d951ea:
      title: Calling the Guru From Afar
      parent: Prayers
    592f041f89f24795bacc441f2878aaa6:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Prayers
    226680f9acdd45318904e62007f4f204:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    a18a9e5b373c47e391c0afef6db8457b:
      title: A Song of Calling the Guru from Afar
      parent: Prayers
    292d0ec6b84340ad8646263f2ea03d7c:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    66a9e80d54f143da81c9905308eb348b:
      title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
        the Great Omniscient Jonangpa from Afar'
      parent: Prayers
    2d40de4da13e473dafa824c825ed24c3:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Prayers
    3ebe334fc6f04a989d807b19b75a3ca0:
      title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling
        the Guru from Afar'
      parent: Prayers
    1ce98ded56204461aa84e83afb1362e0:
      title: Prayer and Call from Afar to the Great Omniscient One
      parent: Prayers
    0a6693aed5284dd395b9484a25384490:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    b6a7d27f87404f4fbb7bce54011a7f07:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Prayers
    99a9aef16667464b88da58d55eb152f6:
      title: Calling the Guru from Afar
      parent: Prayers
created_at: '2022-03-01T03:10:18.230122'
last_modified_at: '2022-03-01T03:10:18.230128'
